import numpy as np
import pandas as pd
import pathlib
import socket
import wandb

import tools as tools


def wrap_angle(angle):
    # Wrap angle to [-pi, pi]
    return (angle + np.pi) % (2 * np.pi) - np.pi


def count_steps(folder):
    return sum(int(str(n).split("-")[-1][:-4]) - 1 for n in folder.glob("*.npz"))


def make_absolute_path(path, on_sagemaker:bool=False):
    """Construct an absolute path from a relative path.

    Args:
        path: Relative path (e.g., 'logs/my_model' or 'workspace/data')
        on_sagemaker: If True, use SageMaker base path; otherwise use home directory

    Returns:
        Absolute path:
        - On SageMaker: /opt/ml/code/{path}
        - Locally: ~/{path}

    Example:
        make_absolute_path('logs/foo', on_sagemaker=True) → /opt/ml/code/logs/foo

    Note:
        When specifying model paths in configs.yaml for SageMaker training:
        - Models are downloaded to /opt/ml/code/logs/ by download_s3_artifacts.py
        - So specify paths as 'logs/model_name' in configs.yaml
        - This function will then resolve to /opt/ml/code/logs/model_name
    """
    if on_sagemaker:
        base = pathlib.Path("/opt/ml/code")
    else:
        base = pathlib.Path.home()

    return base / path


def find_free_port():
    """Find an available port to connect to"""
    # https://stackoverflow.com/questions/1365265/on-localhost-how-do-i-pick-a-free-port-number
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as skt:
        skt.bind(("", 0))
        skt.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        return skt.getsockname()[1]


def load_path(source):
    """
    Loads the autogenerated dataframe containing the sequence of x,y points representing
    the centerline, left boundary and right boundary. If this file doesn't exist yet
    it will be computed here in the following process.

    # Arguments
    - `source::str`: The path to the source track or ref file to read as a dataframe.

    # Returns
    - `::pd.DataFrame`: The sequence of 2D points and their track definition or ref states.
    - `::dict`: A mapping of dataframe column names to their units.
    - `::dict`: A mapping of dataframe column names to their periods. Defaults to 0.
    """
    path_df = pd.read_csv(source, header=[0, 1, 2])

    units, periods = {}, {}
    for col in path_df.columns:
        col_name = col[0]
        units[col_name] = col[1]
        periods[col_name] = None if col[2] == "None" else float(col[2])

    path_df.columns = path_df.columns.get_level_values(0)
    return path_df, units, periods


def cyclical_wrap(val, period=2 * np.pi):
    """
    If period is not None, wraps the value to a range
    of -period/2 to period/2, otherwise just returns in
    """
    result = val
    if period:
        result = ((val + period / 2) % period) - period / 2
    return result


def segment_proportion(start: np.ndarray, end: np.ndarray, query: np.ndarray):
    """
    Calculates the proportion that a query point's perpendicular bisector
    with a segment from start to end has from the start to the end
    """
    vector_ab: np.ndarray = end - start
    vector_aq: np.ndarray = query - start
    aq_proj: np.ndarray = np.sum(vector_aq * vector_ab, axis=-1)
    if len(vector_ab.shape) == 1 and np.linalg.norm(vector_ab) == 0:
        print(f"WARN: 0 distance between {start} and {end}")
    ab_dist = np.maximum(np.linalg.norm(vector_ab, axis=-1), 1e-5)
    a_to_b_prop = aq_proj / ab_dist ** 2
    return a_to_b_prop


def normalize_track_columns(df, target_format='capitalized'):
    """Normalize track CSV column names from various formats to a standard format.

    Args:
        df: DataFrame with track data
        target_format: Target column format:
            - 'capitalized': PathX, PathY, LeftX, LeftY, RightX, RightY (used by PathInterpolator)
            - 'lowercase': path_x, path_y, left_edge_x, left_edge_y, right_edge_x, right_edge_y (used by epic_dynamics)
            - 'slash': refline/x, refline/y, inner_edge/x, inner_edge/y, outer_edge/x, outer_edge/y (used by box2d)

    Returns:
        DataFrame with normalized column names
    """
    # Define mappings from various source formats to all target formats
    format_mappings = {
        'capitalized': {
            # From town format (lowercase with underscores)
            'path_x': 'PathX',
            'path_y': 'PathY',
            'dist': 'Dist',
            'left_edge_x': 'LeftX',
            'left_edge_y': 'LeftY',
            'right_edge_x': 'RightX',
            'right_edge_y': 'RightY',
            'yaw': 'Heading',
            'curvature': 'Curvature',
            # From racing format (with slashes)
            'refline/x': 'PathX',
            'refline/y': 'PathY',
            'inner_edge/x': 'LeftX',
            'inner_edge/y': 'LeftY',
            'outer_edge/x': 'RightX',
            'outer_edge/y': 'RightY',
            's': 'Dist',
        },
        'lowercase': {
            # From racing format (with slashes)
            'inner_edge/x': 'left_edge_x',
            'inner_edge/y': 'left_edge_y',
            'outer_edge/x': 'right_edge_x',
            'outer_edge/y': 'right_edge_y',
            'refline/x': 'path_x',
            'refline/y': 'path_y',
            'refline/z': 'path_z',
            # From capitalized format
            'LeftX': 'left_edge_x',
            'LeftY': 'left_edge_y',
            'RightX': 'right_edge_x',
            'RightY': 'right_edge_y',
            'PathX': 'path_x',
            'PathY': 'path_y',
        },
        'slash': {
            # From town format (lowercase with underscores)
            'left_edge_x': 'inner_edge/x',
            'left_edge_y': 'inner_edge/y',
            'right_edge_x': 'outer_edge/x',
            'right_edge_y': 'outer_edge/y',
            'path_x': 'refline/x',
            'path_y': 'refline/y',
            'path_vx': 'refline/v',
            # From capitalized format
            'LeftX': 'inner_edge/x',
            'LeftY': 'inner_edge/y',
            'RightX': 'outer_edge/x',
            'RightY': 'outer_edge/y',
            'PathX': 'refline/x',
            'PathY': 'refline/y',
        },
    }

    if target_format not in format_mappings:
        raise ValueError(f"Unknown target format: {target_format}. Must be one of {list(format_mappings.keys())}")

    column_mappings = format_mappings[target_format]

    # Build rename dictionary only for columns that need mapping
    rename_dict = {}
    for col in df.columns:
        if col in column_mappings and column_mappings[col] != col:
            rename_dict[col] = column_mappings[col]

    if rename_dict:
        df = df.rename(columns=rename_dict)

    return df, rename_dict


class PathInterpolator:
    def __init__(self, source_file, circuit=False):
        self.path_df, self.units, self.periods = load_path(source_file)
        self.circuit = circuit

        # Detect and normalize column names to handle different CSV formats
        self._normalize_column_names()

        self.X = self.path_df["PathX"].values
        self.Y = self.path_df["PathY"].values
        self.S = self.path_df["Dist"].values
        self.heading = self.path_df["Heading"].values
        self.path = np.stack([self.X, self.Y], axis=-1)
        self.max_query_size = 1e7 // len(self.path)

    def _normalize_column_names(self):
        """Normalize column names from different CSV formats to a standard format."""
        # Use the shared normalize_track_columns function with 'capitalized' format
        self.path_df, rename_dict = normalize_track_columns(self.path_df, target_format='capitalized')

        if rename_dict:
            # Also update units and periods dictionaries
            for old_name, new_name in rename_dict.items():
                if old_name in self.units:
                    self.units[new_name] = self.units.pop(old_name)
                if old_name in self.periods:
                    self.periods[new_name] = self.periods.pop(old_name)

    def _clip_or_mod(self, val):
        if not self.circuit:
            return np.clip(val, 0, len(self.path) - 1)
        return val % len(self.path)

    def nearest_index(self, x, y, s=0):
        """
        Gets the indices and distances of the closest point on the path from the given x,y point.
        The naive approach here is to compare the query point to each point in the entire path
        and returning the index of the point on the path with the lowest distance to the query
        point. Due to memory limits when querying in batch, a batch query is split into groups
        if it has more points than the max query size.

        # Arguments
        - `x::float|np.array{float}`: A float or array of query x positions of the car.
        - `y::float|np.array{float}`: A float or array of query y positions of the car.
        - `s::float|np.array{float}`: A float or array of query s positions of the car.

        # Returns
        - `::np.array{int}`: The index or batch of indices of the nearest point/s on the track path
        """
        query_point = np.stack([x, y], axis=-1)
        batch_shape = query_point.shape[:-1]
        query_point = query_point.reshape([-1, 1, 2])
        num_groups = int(query_point.shape[0] / self.max_query_size) + 1
        query_groups = np.array_split(query_point, num_groups, axis=0)
        ind_groups = []
        for query_group in query_groups:
            diffs = self.path[None] - query_group
            dists = np.linalg.norm(diffs, axis=-1)
            nearest_ind = np.argmin(dists, axis=-1)
            ind_groups.append(nearest_ind)
        nearest_index: np.ndarray = np.concatenate(ind_groups, axis=0)
        nearest_index = nearest_index.reshape(batch_shape)
        return nearest_index

    def nearest_interp_index(self, x, y, s=0):
        """
        Gets the nearest float index by finding the nearest two discrete integer indices of the
        points on the track path that the perpendicular line passing through the x,y point would
        intersect the segment joining the two nearest points. Then the float index is calculated
        as the proportion of distance of the intersect point from the earlier nearest point to
        the next point.

        # Arguments
        - `x::float|np.array{float}`: A float or array of query x positions of the car.
        - `y::float|np.array{float}`: A float or array of query y positions of the car.
        - `s::float|np.array{float}`: A float or array of query s positions of the car.

        # Returns
        - `::np.array{float}`: The indices of the nearest interpolated point(s) on the track path
        """
        nearest_int_index = self.nearest_index(x, y, s)
        # Get the next index that is within the valid index range of the path sequence
        next_index = self._clip_or_mod(nearest_int_index + 1)
        # Making sure the next index is consecutive to the nearest index, negative is ok
        nearest_int_index = next_index - 1
        # Getting the prev index that is consecutive from nearest index, and can also be negative
        prev_index = nearest_int_index - 1

        next_point = self.path[next_index]
        near_point = self.path[nearest_int_index]
        prev_point = self.path[prev_index]
        query_point = np.stack([x, y], axis=-1)

        # Now compare the prev and next index to see which segment with the nearest index will
        # contain the intersection with the perpendicular line passing through the query point
        nearest_point_prop = segment_proportion(prev_point, next_point, near_point)
        query_point_prop = segment_proportion(prev_point, next_point, query_point)
        query_cond = query_point_prop < nearest_point_prop
        next_nearest_int_index = np.where(query_cond, prev_index, next_index)

        # Getting the two nearest points such that the segment between them intersects the
        # perpendicular line passing through the query point.
        ind_a = nearest_int_index
        ind_b = next_nearest_int_index
        point_a = self.path[ind_a]
        point_b = self.path[ind_b]

        # Calculate proportion of distance along the segment that the perpendicular intersect lies.
        a_to_b_prop = segment_proportion(point_a, point_b, query_point)
        clipped_prop = np.clip(a_to_b_prop, 0, 1)
        nearest_index = ind_a + clipped_prop * (ind_b - ind_a)
        return nearest_index

    def convert_xy_to_state(self, x, y, s=0):
        """
        Gets the nearest interpolated index from the given x,y point and then interpolates all
        possible state values for each param provided in the path dataframe.

        # Arguments
        - `x::float|np.array{float}`: A float or array of query x positions of the car.
        - `y::float|np.array{float}`: A float or array of query y positions of the car.
        - `s::float|np.array{float}`: A float or array of query s positions of the car.

        # Returns
        - `::dict`: The interpolated path dataframe.
        - `::float`: Cross product of found using interp points and prev/next reference points.
        """
        index = self.nearest_interp_index(x, y, s)
        index = self._clip_or_mod(index)
        ind_low = np.floor(index).astype(int)
        ind_high = self._clip_or_mod(ind_low + 1)
        ind_prop = index - ind_low
        state_dict = {}
        for col_name in self.path_df.columns:
            val_low = self.path_df[col_name].values[ind_low]
            val_high = self.path_df[col_name].values[ind_high]
            val_diff = cyclical_wrap(val_high - val_low, self.periods[col_name])
            val_interp = val_low + ind_prop * val_diff
            val_interp = cyclical_wrap(val_interp, self.periods[col_name])
            state_dict[col_name] = val_interp

        point = np.stack([x, y], axis=-1)
        prev_point = np.stack([self.X[ind_low], self.Y[ind_low]], axis=-1)
        next_point = np.stack([self.X[ind_high], self.Y[ind_high]], axis=-1)

        start_to_point = point - prev_point
        start_to_end = next_point - prev_point
        cross_product = np.cross(start_to_end, start_to_point)

        return state_dict, cross_product


class ProcessEpisodeWrap:
    """Processes and logs information about each episode in the simulation, useful for both training and evaluation.

    Class Methods:
        process_episode: Logs episode data, computes scores, and manages rendering.

    """

    collision_count = 0
    eval_scores = []
    eval_lengths = []
    last_step_at_eval = -1
    eval_done = False
    eval_progress = []

    @classmethod
    def process_episode(
        cls,
        config,
        logger,
        mode,
        train_eps,
        eval_eps,
        renderer,
        episode,
        info,
    ):
        """
        Processes and logs a single episode, computing scores and handling rendering.

        Parameters:
            config: Configuration settings for the episode processing.
            logger: Logger for recording episode metrics.
            mode: The mode of operation ('train' or 'eval').
            train_eps: Training episodes data.
            eval_eps: Evaluation episodes data.
            renderer: Function or object used for rendering the episode.
            episode: Data for the episode to process.
            info: Additional information about the episode.

        Returns:
            None
        """
        directory = dict(train=config.traindir, eval=config.evaldir)[mode]
        cache = dict(train=train_eps, eval=eval_eps)[mode]
        # this saved episodes is given as train_eps or eval_eps from next call
        filename = tools.save_episodes(directory, [episode])[0]
        length = len(episode["reward"]) - 1
        score = float(episode["reward"].astype(np.float64).sum())
        progress = float(sum(info["progress"]))
        collisions = int(sum(info["collisions"]))
        intent_specific_reward = float(sum(info["intent_specific_reward"]))
        avg_action_discontinuity = 0.0  # float(np.mean(info["action_discontinuity"]))
        # print([f"{k}: {v.shape}" for k, v in episode.items()])

        cache[str(filename)] = episode
        if mode == "train":
            total = 0
            for keyname, ep in reversed(sorted(cache.items(), key=lambda x: x[0])):
                if not config.dataset_size or total <= config.dataset_size - length:
                    total += len(ep["reward"]) - 1
                else:
                    del cache[keyname]
            wandb.log({"dataset_size": total})
            logger.scalar("dataset_size", total)
            # use dataset_size as log step for a condition of envs > 1
            log_step = total * config.action_repeat
        elif mode == "eval":
            # ***** REMOVE DOMAIN-SPECIFIC CODE *****
            if config.render_box2d:
                # print(f"  ACTIONS, STATES {info['agent_actions'][0]}, {info['agent_states'][0]}")
                renderer = renderer(info["agent_actions"], info["agent_states"], episode["reward"], info.get("reward_components", None))
                video = renderer.render_video(mode)

                # TODO Fix the shaping upstream
                video = video[:, 0, :, :, :] if video.ndim == 5 else video

            # keep only last item for saving memory
            while len(cache) > 1:
                # FIFO
                cache.popitem()
            # start counting scores for evaluation
            if cls.last_step_at_eval != logger.step:
                cls.eval_scores = []
                cls.eval_lengths = []
                cls.eval_done = False
                cls.last_step_at_eval = logger.step

            cls.eval_scores.append(score)
            cls.eval_lengths.append(length)
            cls.eval_progress.append(progress)
            # ignore if number of eval episodes exceeds eval_episode_num
            if len(cls.eval_scores) < config.eval_episode_num or cls.eval_done:
                return
            score = np.mean(cls.eval_scores)
            length = np.mean(cls.eval_lengths)
            progress = np.mean(cls.eval_progress)
            episode_num = len(cls.eval_scores)
            log_step = logger.step
            if config.render_box2d:
                logger.video(f"{mode}_policy", video[None])
                # pass array of dim (batch, time, channel, width, height)
                wandb.log({f"{mode}_policy": wandb.Video(np.moveaxis(video[None], -1, -3))})
            cls.eval_done = True

        print(f"{mode.title()} episode has {length} steps and return {score:.1f}.")
        wandb.log(
            {
                f"metrics/{mode}_return": score,
                f"{mode}_length": length,
                f"{mode}_episodes": len(cache) if mode == "train" else episode_num,
                f"metrics/{mode}_progress": progress,
                f"metrics/{mode}_collisions": collisions,
                f"metrics/{mode}_intent_specific_reward": np.mean(info["intent_specific_reward"]),
            }
        )
        for k in ["speed", "intervention_norm"]:
            avg_v = np.array(info[k]).mean()
            max_v = max(info[k])
            wandb.log({f"metrics/{mode}_average_{k}": avg_v})
            wandb.log({f"metrics/{mode}_max_{k}": max_v})
            logger.scalar(f"{mode}_average_{k}", avg_v)
            logger.scalar(f"{mode}_max_{k}", max_v)
        logger.scalar(f"{mode}_return", score)
        logger.scalar(f"{mode}_length", length)
        logger.scalar(f"{mode}_episodes", len(cache) if mode == "train" else episode_num)
        logger.scalar(f"{mode}_progress", progress)
        logger.scalar(f"{mode}_collisions", collisions)
        logger.scalar(f"{mode}_intent_specific_reward", np.mean(info["intent_specific_reward"]))
        logger.scalar("average human or AI action discontinuity", avg_action_discontinuity)
        wandb.log({"average human or AI action discontinuity": avg_action_discontinuity})
        logger.write(step=log_step)
